### ISSUE TITLE
Subscription to some events fails

### ISSUE THREAD

**Issue by vkodin** [joliveros/bitmex-websocket#7]
Subscription to some channels that require authentication, particularly 'order', causes a KeyError:

```
instrument = Instrument(symbol='XBTUSD',
                        channels=['order'],
                        maxTableLength=5,
                        shouldAuth=True)

instrument.on('order', lambda channel, data: print(channel, data))
```

```
2017-08-25 00:14:28 ERROR [bitmex_websocket.websocket:235] Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/bitmex_websocket/websocket.py", line 226, in on_message
    self.emit(event_name, message)
  File "/usr/local/lib/python3.4/dist-packages/pyee/__init__.py", line 148, in emit
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bitmex_websocket/instrument.py", line 192, in on_action
    self.update_keys_in_table(table, data[0])
  File "/usr/local/lib/python3.4/dist-packages/bitmex_websocket/instrument.py", line 202, in update_keys_in_table
    self.data[table].update(update)
KeyError: 'order'
```

**Comment by joliveros** [comment]
This one is going to take a bit to fix. I'll reference this issue once I've got a PR WIP.

thanks for using my lib!

**Comment by darshanlol** [comment]
Still happens, need help?
